services:
    minecraft:
        image: amazoncorretto:17
        volumes:
            - ${MINECRAFT_DIR}:/minecraft
        working_dir: /minecraft
        ports:
            - ${SERVER_PORT}:25565
            - ${RCON_PORT}:25575
        entrypoint: ["java", "-Xms${JVM_HEAP_SIZE}", "-Xmx${JVM_HEAP_SIZE}", "-jar", "${SERVER_JAR}", "${OPTION}"]