services:
    minecraft:
        image: eclipse-temurin:21
        volumes:
            - ${MINECRAFT_DIR}:/minecraft
            - ./:/robotmc
            - ./backup:/backup
        working_dir: /robotmc
        ports:
            - ${SERVER_PORT}:25565
            - ${RCON_PORT}:25575
        entrypoint: ["/bin/bash", "./main.sh"]
