services:
    minecraft:
        image: amazoncorretto:17
        volumes:
            - ~/minecraft:/minecraft
        working_dir: /minecraft
        ports:
            - 25565:25565
            - 25575:25575
        entrypoint: ["java", "-Xms1024M", "-Xmx1024M", "-jar", "server.jar", "nogui"]