name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Minecraft Server
        uses: wei/curl@master
        with:
          args: ${{ vars.SERVER_JAR_DOWNLOAD_URL }} -o ~/minecraft/server.jar

      - name: Start Minecraft Server
        run: |
          sh main.sh
